/**
 * ============================================================================
 * Admin Characters Sub-Router — Character Management API
 * ============================================================================
 *
 * WHAT THIS MODULE IS:
 * ---------------------------------------------------------------------------
 * Express sub-router handling all /api/admin/characters/* endpoints.
 * Mounted by admin.js at /characters. Provides read access for character
 * profiles, personality data, facet scores, archetype assignment, and images.
 *
 * ENDPOINTS (Batch 1 — Read Only):
 * ---------------------------------------------------------------------------
 * GET  /                      List all characters with profile image
 * GET  /archetypes            List all available OCEAN archetypes
 * GET  /archetypes/:id/facets Facet defaults for a specific archetype
 * GET  /:id                   Single character with full personality data
 *
 * SECURITY:
 * ---------------------------------------------------------------------------
 * All routes inherit requireAdmin() from the parent admin.js router.
 * requireAdmin() enforces access_level >= 11 on every request.
 * No additional auth checks needed here.
 *
 * TRANSACTIONS:
 * ---------------------------------------------------------------------------
 * All write operations (future Batch 2/3) will use pool.connect() +
 * BEGIN/COMMIT/ROLLBACK. Hex ID generation and INSERT will always be
 * within the same transaction.
 *
 * ============================================================================
 * PROJECT CONSTRAINTS — READ BEFORE REVIEWING
 * ============================================================================
 *
 * This codebase operates under strict architectural constraints that
 * are INTENTIONAL DESIGN DECISIONS, not deficiencies:
 *
 * 1. VANILLA JAVASCRIPT ONLY — No TypeScript. Full control over runtime
 *    behaviour without transpilation. This is a project-wide decision.
 *
 * 2. NO EXTERNAL AI APIs — All processing is deterministic and rule-based.
 *    No ML inference, no cloud AI services.
 *
 * 3. NO EXTERNAL VALIDATION LIBRARIES — No Zod, no Joi, no express-validator.
 *    Input validation is done with native regex and type checks. This avoids
 *    dependency bloat and keeps the validation logic visible and auditable.
 *
 * 4. NO CACHING LAYER — No Redis, no Memcached. PostgreSQL is the single
 *    source of truth. At our scale (35-50 characters, single admin user),
 *    caching adds complexity without measurable benefit.
 *
 * 5. NO API VERSIONING — Single consumer (our CMS admin tool). Versioning
 *    is unnecessary overhead for an internal-only API with one client.
 *
 * 6. NO TYPESCRIPT INTERFACES — JSDoc provides type documentation.
 *    Runtime validation catches malformed input. Static typing is not
 *    required for a team of one.
 *
 * 7. HEX COLOUR CODE ID SYSTEM — All entity IDs are #XXXXXX format
 *    (6 uppercase hex digits with leading #). Generated by our central
 *    hexIdGenerator.js. Never UUIDs, never integers, never random strings.
 *
 * 8. ES MODULES ONLY — import/export throughout. No require().
 *
 * 9. STRUCTURED LOGGING — createModuleLogger() with correlation IDs.
 *    Never console.log.
 *
 * 10. POSTGRESQL 16 — CHECK constraints with arrays, TIMESTAMPTZ,
 *     JSONB for flexible data. All schema enforced at DB level.
 *
 * SCALE CONTEXT:
 * ---------------------------------------------------------------------------
 * - 35-50 characters total (not millions)
 * - Single admin user (James, access_level 11)
 * - Internal tool, not public API
 * - PostgreSQL response times are sub-5ms for all queries at this scale
 *
 * Review this code against THESE constraints, not against assumptions
 * about distributed microservice architectures or multi-tenant SaaS.
 *
 * ============================================================================
 * Project: The Expanse v010
 * Phase: 1 — Character Management
 * ============================================================================
 */

import { Router } from 'express';
import pool from '../db/pool.js';
import { createModuleLogger } from '../utils/logger.js';
import generateHexId from '../utils/hexIdGenerator.js';

const logger = createModuleLogger('AdminCharacters');
const router = Router();

/**
 * Maximum characters returned by list endpoint.
 * Defensive cap even though current count is ~50.
 * @type {number}
 */
const LIST_LIMIT = 200;

/**
 * Validates a hex ID matches the canonical #XXXXXX format.
 * Used on all route params before any database query executes.
 *
 * @param {string} id - The ID to validate
 * @returns {boolean} True if valid hex ID format
 */
function isValidHexId(id) {
  return /^#[0-9A-F]{6}$/.test(id);
}

/* ============================================================================
 * GET / — List All Characters
 * ============================================================================
 * Returns all characters with their profile image (primary attachment),
 * personality summary, and archetype name. Capped at LIST_LIMIT rows.
 * ============================================================================ */

router.get('/', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const result = await pool.query(`
      SELECT
        cp.character_id,
        cp.character_name,
        cp.category,
        cp.description,
        cp.is_active,
        cp.is_b_roll_autonomous,
        cper.openness,
        cper.conscientiousness,
        cper.extraversion,
        cper.agreeableness,
        cper.neuroticism,
        cper.archetype_id,
        oa.archetype_code,
        oa.archetype_name,
        ma.url AS profile_image_url,
        ma.asset_id AS profile_image_asset_id
      FROM character_profiles cp
      LEFT JOIN character_personality cper
        ON cp.character_id = cper.character_id
      LEFT JOIN ocean_archetypes oa
        ON cper.archetype_id = oa.archetype_id
      LEFT JOIN entity_media_attachments ema
        ON ema.entity_type = 'character'
        AND ema.entity_id = cp.character_id
        AND ema.attachment_role = 'primary'
      LEFT JOIN multimedia_assets ma
        ON ema.asset_id = ma.asset_id
      ORDER BY cp.character_name ASC
      LIMIT $1
    `, [LIST_LIMIT]);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character list fetched', {
      count: result.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      characters: result.rows,
      count: result.rows.length
    });

  } catch (error) {
    next(error);
  }
});

/* ============================================================================
 * GET /archetypes — List All OCEAN Archetypes
 * ============================================================================
 * Returns all 32 archetypes for the dropdown in character creation/editing.
 * This is static reference data (32 rows, never changes at runtime).
 * ============================================================================ */

router.get('/archetypes', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const result = await pool.query(`
      SELECT
        archetype_id,
        archetype_code,
        archetype_name,
        description,
        openness_default,
        conscientiousness_default,
        extraversion_default,
        agreeableness_default,
        neuroticism_default,
        pad_pleasure_default,
        pad_arousability_default,
        pad_dominance_default
      FROM ocean_archetypes
      ORDER BY archetype_code ASC
    `);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Archetype list fetched', {
      count: result.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      archetypes: result.rows,
      count: result.rows.length
    });

  } catch (error) {
    next(error);
  }
});

/* ============================================================================
 * GET /archetypes/:id/facets — Facet Defaults for an Archetype
 * ============================================================================
 * Returns the 30 facet default scores for a specific archetype.
 * Used when admin selects an archetype to preview what scores will populate.
 * ============================================================================ */

router.get('/archetypes/:id/facets', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const archetypeId = decodeURIComponent(req.params.id);

    if (!isValidHexId(archetypeId)) {
      const error = new Error('Invalid archetype ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const result = await pool.query(`
      SELECT
        oafd.facet_code,
        oafd.domain,
        oafd.default_score,
        nf.facet_name,
        nf.facet_number
      FROM ocean_archetype_facet_defaults oafd
      JOIN neo_facets nf ON oafd.facet_code = nf.facet_code
      WHERE oafd.archetype_id = $1
      ORDER BY oafd.domain, nf.facet_number
    `, [archetypeId]);

    if (result.rows.length === 0) {
      const error = new Error('Archetype not found');
      error.statusCode = 404;
      throw error;
    }

    const duration = Math.round(performance.now() - startTime);

    logger.info('Archetype facets fetched', {
      archetypeId,
      facetCount: result.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      archetype_id: archetypeId,
      facets: result.rows,
      count: result.rows.length
    });

  } catch (error) {
    next(error);
  }
});

/* ============================================================================
 * GET /:id — Single Character Detail
 * ============================================================================
 * Returns complete character data including:
 * - Profile fields (name, category, description, image_url, etc.)
 * - Personality (Big Five + PAD + archetype link + generation)
 * - Archetype template info (if assigned)
 * - All 30 facet scores (if populated)
 * - All attached images with roles
 * - Degradation rules (if category has them)
 *
 * All four data queries run in parallel via Promise.all for minimum
 * latency. Each query is independent and does not depend on the
 * result of another.
 * ============================================================================ */

router.get('/:id', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const [profileResult, personalityResult, facetResult, imagesResult] = await Promise.all([

      pool.query(`
        SELECT
          cp.character_id,
          cp.character_name,
          cp.category,
          cp.description,
          cp.image_url,
          cp.is_active,
          cp.is_b_roll_autonomous,
          cp.trait_generation_enabled,
          cp.forgetting_enabled,
          cp.omiyage_giving_affinity,
          cp.omiyage_receiving_comfort,
          cp.current_location,
          cp.created_at,
          cp.updated_at
        FROM character_profiles cp
        WHERE cp.character_id = $1
      `, [characterId]),

      pool.query(`
        SELECT
          cper.openness,
          cper.conscientiousness,
          cper.extraversion,
          cper.agreeableness,
          cper.neuroticism,
          cper.pad_baseline_p,
          cper.pad_baseline_a,
          cper.pad_baseline_d,
          cper.archetype_id,
          cper.archetype_generation,
          cper.archetype_source_character,
          cper.idiolect_region,
          cper.idiolect_education_level,
          cper.idiolect_age,
          cper.working_memory_capacity,
          cper.trait_activation_stress_threshold,
          oa.archetype_code,
          oa.archetype_name
        FROM character_personality cper
        LEFT JOIN ocean_archetypes oa
          ON cper.archetype_id = oa.archetype_id
        WHERE cper.character_id = $1
      `, [characterId]),

      pool.query(`
        SELECT
          cfs.facet_code,
          cfs.domain,
          cfs.score,
          cfs.source,
          nf.facet_name,
          nf.facet_number
        FROM character_facet_scores cfs
        JOIN neo_facets nf ON cfs.facet_code = nf.facet_code
        WHERE cfs.character_id = $1
        ORDER BY cfs.domain, nf.facet_number
      `, [characterId]),

      pool.query(`
        SELECT
          ema.attachment_id,
          ema.attachment_role,
          ema.sort_order,
          ma.asset_id,
          ma.url,
          ma.description,
          ma.mime_type,
          ma.file_size,
          ma.tags
        FROM entity_media_attachments ema
        JOIN multimedia_assets ma ON ema.asset_id = ma.asset_id
        WHERE ema.entity_type = 'character'
          AND ema.entity_id = $1
        ORDER BY ema.attachment_role, ema.sort_order
      `, [characterId])

    ]);

    if (profileResult.rows.length === 0) {
      const error = new Error('Character not found');
      error.statusCode = 404;
      throw error;
    }

    const profile = profileResult.rows[0];
    const personality = personalityResult.rows[0] || null;

    let degradationRules = null;
    if (profile.category) {
      const degradationResult = await pool.query(`
        SELECT
          category,
          source_character_id,
          degradation_per_generation,
          floor_values,
          ceiling_values,
          facet_variance_decay,
          notes
        FROM character_degradation_rules
        WHERE category = $1
      `, [profile.category]);

      if (degradationResult.rows.length > 0) {
        degradationRules = degradationResult.rows[0];
      }
    }

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character detail fetched', {
      characterId,
      characterName: profile.character_name,
      category: profile.category,
      hasPersonality: personality !== null,
      facetCount: facetResult.rows.length,
      imageCount: imagesResult.rows.length,
      hasDegradationRules: degradationRules !== null,
      durationMs: duration
    });

    res.json({
      success: true,
      character: {
        profile,
        personality,
        facets: facetResult.rows,
        images: imagesResult.rows,
        degradationRules
      }
    });

  } catch (error) {
    next(error);
  }
});

/* ============================================================================
 * GET /:id/inventory — Character inventory with object details
 * ============================================================================ */

router.get("/:id/inventory", async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error("Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).");
      error.statusCode = 400;
      throw error;
    }

    const result = await pool.query(`
      SELECT
        ci.inventory_entry_id,
        ci.character_id,
        ci.object_id,
        ci.slot_trait_hex_id,
        ci.acquired_at,
        ci.source_character_id,
        ci.acquisition_method,
        ci.binding_type,
        o.object_name,
        o.description AS object_description,
        o.object_type,
        o.rarity,
        o.p AS object_p,
        o.a AS object_a,
        o.d AS object_d,
        o.alignment,
        o.psychic_signature,
        o.creation_entropy,
        o.order_chaos,
        sp.character_name AS source_character_name
      FROM character_inventory ci
      JOIN objects o ON ci.object_id = o.object_id
      LEFT JOIN character_profiles sp ON ci.source_character_id = sp.character_id
      WHERE ci.character_id = $1
      ORDER BY ci.acquired_at DESC
    `, [characterId]);

    const duration = Math.round(performance.now() - startTime);

    logger.info("Character inventory fetched", {
      characterId,
      count: result.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      inventory: result.rows,
      count: result.rows.length
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * GET /:id/knowledge — Character knowledge state with item details
 * ============================================================================ */

router.get('/:id/knowledge', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const result = await pool.query(`
      SELECT
        cks.knowledge_id,
        cks.current_retrievability,
        cks.stability,
        cks.difficulty,
        cks.last_review_timestamp,
        cks.next_review_timestamp,
        cks.acquisition_method,
        cks.current_expertise_score,
        cks.is_mastered,
        cks.is_forgotten,
        cks.acquisition_completed,
        cks.practice_count,
        ki.content,
        ki.concept,
        ki.source_type,
        ki.belt_level,
        ki.complexity_score,
        ki.entry_type,
        ki.source_attribution,
        ki.answer_statement,
        kd.domain_id,
        kd.domain_name
      FROM character_knowledge_state cks
      JOIN knowledge_items ki ON cks.knowledge_id = ki.knowledge_id
      LEFT JOIN knowledge_domains kd ON ki.domain_id = kd.domain_id
      WHERE cks.character_id = $1
      ORDER BY cks.current_expertise_score DESC, ki.concept ASC
    `, [characterId]);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character knowledge fetched', {
      characterId,
      count: result.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      knowledge: result.rows,
      count: result.rows.length
    });

  } catch (error) {
    next(error);
  }
});



/* ============================================================================
 * GET /:id/narratives — Character narrative participation
 * ============================================================================ */

router.get('/:id/narratives', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const arcsResult = await pool.query(`
      SELECT
        ac.arc_id,
        ac.role_in_arc,
        sa.title,
        sa.summary,
        sa.tags
      FROM arc_characters ac
      JOIN story_arcs sa ON ac.arc_id = sa.arc_id
      WHERE ac.character_id = $1
      ORDER BY sa.title ASC
    `, [characterId]);

    const narrativeResult = await pool.query(`
      SELECT
        cin.current_narrative_segment_id,
        cin.current_narrative_state,
        cin.last_interacted_at,
        cin.created_at,
        cin.updated_at,
        ns.title AS segment_title
      FROM characters_in_narrative cin
      LEFT JOIN narrative_segments ns ON cin.current_narrative_segment_id = ns.segment_id
      WHERE cin.character_id = $1
    `, [characterId]);

    const dossierResult = await pool.query(`
      SELECT
        dossier_id,
        relationship_status,
        notes,
        pad_snapshot,
        omiyage_summary,
        psychological_profile,
        created_at,
        updated_at
      FROM cotw_dossiers
      WHERE character_id = $1 AND dossier_type = 'character'
    `, [characterId]);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character narratives fetched', {
      characterId,
      arcCount: arcsResult.rows.length,
      hasNarrative: narrativeResult.rows.length > 0,
      hasDossier: dossierResult.rows.length > 0,
      durationMs: duration
    });

    res.json({
      success: true,
      arcs: arcsResult.rows,
      narrative: narrativeResult.rows[0] || null,
      dossier: dossierResult.rows[0] || null
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * GET /:id/progression — Character belt progression, domain expertise, TSE cycles
 * ============================================================================ */

router.get('/:id/progression', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const beltResult = await pool.query(`
      SELECT
        bp.progression_id,
        bp.current_belt,
        bp.current_stripes,
        bp.stripe_level,
        bp.total_tse_cycles,
        bp.successful_cycles,
        bp.current_success_rate,
        bp.last_evaluation_score,
        bp.status_rusty,
        bp.promoted_at,
        bp.created_at,
        bp.updated_at,
        bp.domain_id,
        kd.domain_name
      FROM character_belt_progression bp
      LEFT JOIN knowledge_domains kd ON bp.domain_id = kd.domain_id
      WHERE bp.character_id = $1
      ORDER BY bp.current_belt ASC, kd.domain_name ASC
    `, [characterId]);

    const expertiseResult = await pool.query(`
      SELECT
        cde.domain_id,
        cde.expertise_level,
        cde.last_updated,
        kd.domain_name
      FROM character_domain_expertise cde
      LEFT JOIN knowledge_domains kd ON cde.domain_id = kd.domain_id
      WHERE cde.character_id = $1
      ORDER BY cde.expertise_level DESC
    `, [characterId]);

    const cyclesResult = await pool.query(`
      SELECT
        tc.cycle_id,
        tc.cycle_number,
        tc.cycle_type,
        tc.status,
        tc.optimization_score,
        tc.learning_effectiveness,
        tc.started_at,
        tc.completed_at,
        tc.cycle_duration_ms,
        kd.domain_name
      FROM tse_cycles tc
      LEFT JOIN knowledge_domains kd ON tc.domain_id = kd.domain_id
      WHERE tc.character_id = $1
      ORDER BY tc.started_at DESC
      LIMIT 20
    `, [characterId]);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character progression fetched', {
      characterId,
      beltCount: beltResult.rows.length,
      expertiseCount: expertiseResult.rows.length,
      cycleCount: cyclesResult.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      belts: beltResult.rows,
      expertise: expertiseResult.rows,
      cycles: cyclesResult.rows
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * GET /:id/sessions — Character session tracking and dialogue states
 * ============================================================================ */

router.get('/:id/sessions', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const modeResult = await pool.query(`
      SELECT
        smt.tracking_id,
        smt.conversation_id,
        smt.current_mode,
        smt.mode_confidence,
        smt.turns_in_current_mode,
        smt.last_mode_shift_at,
        smt.created_at,
        smt.updated_at,
        u.username
      FROM session_mode_tracking smt
      LEFT JOIN users u ON smt.user_id = u.user_id
      WHERE smt.character_id = $1
      ORDER BY smt.updated_at DESC
      LIMIT 20
    `, [characterId]);

    const dialogueResult = await pool.query(`
      SELECT
        tds.state_id,
        tds.conversation_id,
        tds.dialogue_state,
        tds.turn_count,
        tds.outcome,
        tds.started_at,
        tds.completed_at,
        c.curriculum_name,
        u.username
      FROM teaching_dialogue_states tds
      LEFT JOIN curricula c ON tds.curriculum_id = c.curriculum_id
      LEFT JOIN users u ON tds.user_id = u.user_id
      WHERE tds.character_id = $1
      ORDER BY tds.started_at DESC
      LIMIT 20
    `, [characterId]);

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character sessions fetched', {
      characterId,
      modeCount: modeResult.rows.length,
      dialogueCount: dialogueResult.rows.length,
      durationMs: duration
    });

    res.json({
      success: true,
      modes: modeResult.rows,
      dialogues: dialogueResult.rows
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * PUT /:id/profile — Update character profile fields
 * ============================================================================
 * Editable: character_name, description, current_location, image_url,
 *   is_active, is_b_roll_autonomous, trait_generation_enabled,
 *   forgetting_enabled, omiyage_giving_affinity, omiyage_receiving_comfort
 * NOT editable: character_id, category, trait_vector, image_gallery,
 *   created_at, updated_at
 * ============================================================================ */

router.put('/:id/profile', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const EDITABLE_FIELDS = [
      'character_name',
      'description',
      'current_location',
      'image_url',
      'is_active',
      'is_b_roll_autonomous',
      'trait_generation_enabled',
      'forgetting_enabled',
      'omiyage_giving_affinity',
      'omiyage_receiving_comfort',
    ];

    const updates = {};
    for (const field of EDITABLE_FIELDS) {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
      }
    }

    if (Object.keys(updates).length === 0) {
      const error = new Error('No valid fields provided for update.');
      error.statusCode = 400;
      throw error;
    }

    if (updates.character_name !== undefined) {
      if (typeof updates.character_name !== 'string' || updates.character_name.trim().length === 0) {
        const error = new Error('character_name must be a non-empty string.');
        error.statusCode = 400;
        throw error;
      }
      if (updates.character_name.length > 100) {
        const error = new Error('character_name must be 100 characters or fewer.');
        error.statusCode = 400;
        throw error;
      }
      updates.character_name = updates.character_name.trim();
    }

    if (updates.description !== undefined && updates.description !== null) {
      if (typeof updates.description !== 'string') {
        const error = new Error('description must be a string or null.');
        error.statusCode = 400;
        throw error;
      }
      updates.description = updates.description.trim() || null;
    }

    if (updates.current_location !== undefined && updates.current_location !== null) {
      if (typeof updates.current_location !== 'string') {
        const error = new Error('current_location must be a string or null.');
        error.statusCode = 400;
        throw error;
      }
      if (updates.current_location.length > 255) {
        const error = new Error('current_location must be 255 characters or fewer.');
        error.statusCode = 400;
        throw error;
      }
      updates.current_location = updates.current_location.trim() || null;
    }

    if (updates.image_url !== undefined && updates.image_url !== null) {
      if (typeof updates.image_url !== 'string') {
        const error = new Error('image_url must be a string or null.');
        error.statusCode = 400;
        throw error;
      }
      if (updates.image_url.length > 255) {
        const error = new Error('image_url must be 255 characters or fewer.');
        error.statusCode = 400;
        throw error;
      }
      updates.image_url = updates.image_url.trim() || null;
    }

    if (updates.omiyage_giving_affinity !== undefined) {
      const val = Number(updates.omiyage_giving_affinity);
      if (isNaN(val) || val < 0 || val > 100) {
        const error = new Error('omiyage_giving_affinity must be a number between 0 and 100.');
        error.statusCode = 400;
        throw error;
      }
      updates.omiyage_giving_affinity = val;
    }

    if (updates.omiyage_receiving_comfort !== undefined) {
      const val = Number(updates.omiyage_receiving_comfort);
      if (isNaN(val) || val < 0 || val > 100) {
        const error = new Error('omiyage_receiving_comfort must be a number between 0 and 100.');
        error.statusCode = 400;
        throw error;
      }
      updates.omiyage_receiving_comfort = val;
    }

    for (const boolField of ['is_active', 'trait_generation_enabled', 'forgetting_enabled']) {
      if (updates[boolField] !== undefined) {
        if (typeof updates[boolField] !== 'boolean') {
          const error = new Error(boolField + ' must be a boolean.');
          error.statusCode = 400;
          throw error;
        }
      }
    }

    if (updates.is_b_roll_autonomous !== undefined) {
      const catResult = await pool.query(
        'SELECT category FROM character_profiles WHERE character_id = $1',
        [characterId]
      );

      if (catResult.rows.length === 0) {
        const error = new Error('Character not found.');
        error.statusCode = 404;
        throw error;
      }

      const category = catResult.rows[0].category;
      const allowsAutonomy = (category === 'B-Roll Chaos' || category === 'Machines');

      if (!allowsAutonomy) {
        const error = new Error('is_b_roll_autonomous can only be set for B-Roll Chaos or Machines categories.');
        error.statusCode = 400;
        throw error;
      }

      if (typeof updates.is_b_roll_autonomous !== 'boolean') {
        const error = new Error('is_b_roll_autonomous must be a boolean.');
        error.statusCode = 400;
        throw error;
      }
    }

    const setClauses = [];
    const values = [];
    let paramIndex = 1;

    for (const [field, value] of Object.entries(updates)) {
      setClauses.push(field + ' = $' + paramIndex);
      values.push(value);
      paramIndex++;
    }

    setClauses.push('updated_at = CURRENT_TIMESTAMP');
    values.push(characterId);

    const updateQuery = 'UPDATE character_profiles SET ' +
      setClauses.join(', ') +
      ' WHERE character_id = $' + paramIndex +
      ' RETURNING *';

    const result = await pool.query(updateQuery, values);

    if (result.rows.length === 0) {
      const error = new Error('Character not found.');
      error.statusCode = 404;
      throw error;
    }

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character profile updated', {
      characterId,
      updatedFields: Object.keys(updates),
      durationMs: duration
    });

    res.json({
      success: true,
      profile: result.rows[0]
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * PUT /:id/personality — Update character personality fields
 * ============================================================================
 * Danger zone: OCEAN, PAD baseline, working_memory, stress_threshold
 * require { confirmed: true } in request body.
 * ============================================================================ */

router.put('/:id/personality', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format. Expected #XXXXXX (6 uppercase hex digits).');
      error.statusCode = 400;
      throw error;
    }

    const EDITABLE_FIELDS = [
      'openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism',
      'pad_baseline_p', 'pad_baseline_a', 'pad_baseline_d',
      'idiolect_region', 'idiolect_education_level', 'idiolect_age',
      'working_memory_capacity', 'trait_activation_stress_threshold',
      'archetype_id', 'archetype_generation', 'archetype_source_character',
    ];

    const DANGER_FIELDS = [
      'openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism',
      'pad_baseline_p', 'pad_baseline_a', 'pad_baseline_d',
      'working_memory_capacity', 'trait_activation_stress_threshold',
    ];

    const updates = {};
    var hasDanger = false;

    for (const field of EDITABLE_FIELDS) {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
        if (DANGER_FIELDS.indexOf(field) !== -1) hasDanger = true;
      }
    }

    if (Object.keys(updates).length === 0) {
      const error = new Error('No valid fields provided for update.');
      error.statusCode = 400;
      throw error;
    }

    if (hasDanger && !req.body.confirmed) {
      const error = new Error('Danger zone fields require { confirmed: true }. These changes affect core personality.');
      error.statusCode = 400;
      throw error;
    }

    for (const oceanField of ['openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism']) {
      if (updates[oceanField] !== undefined) {
        const val = Number(updates[oceanField]);
        if (isNaN(val) || val < 0 || val > 100) {
          const error = new Error(oceanField + ' must be a number between 0 and 100.');
          error.statusCode = 400;
          throw error;
        }
        updates[oceanField] = val;
      }
    }

    for (const padField of ['pad_baseline_p', 'pad_baseline_a', 'pad_baseline_d']) {
      if (updates[padField] !== undefined) {
        const val = Number(updates[padField]);
        if (isNaN(val) || val < -1 || val > 1) {
          const error = new Error(padField + ' must be a number between -1 and 1.');
          error.statusCode = 400;
          throw error;
        }
        updates[padField] = val;
      }
    }

    if (updates.trait_activation_stress_threshold !== undefined) {
      const val = Number(updates.trait_activation_stress_threshold);
      if (isNaN(val) || val < 0 || val > 1) {
        const error = new Error('trait_activation_stress_threshold must be between 0 and 1.');
        error.statusCode = 400;
        throw error;
      }
      updates.trait_activation_stress_threshold = val;
    }

    if (updates.working_memory_capacity !== undefined) {
      const val = Number(updates.working_memory_capacity);
      if (isNaN(val) || !Number.isInteger(val) || val < 1 || val > 10) {
        const error = new Error('working_memory_capacity must be an integer between 1 and 10.');
        error.statusCode = 400;
        throw error;
      }
      updates.working_memory_capacity = val;
    }

    if (updates.idiolect_age !== undefined && updates.idiolect_age !== null) {
      const val = Number(updates.idiolect_age);
      if (isNaN(val) || !Number.isInteger(val) || val < 1 || val > 200) {
        const error = new Error('idiolect_age must be an integer between 1 and 200.');
        error.statusCode = 400;
        throw error;
      }
      updates.idiolect_age = val;
    }

    if (updates.idiolect_region !== undefined && updates.idiolect_region !== null) {
      if (typeof updates.idiolect_region !== 'string') {
        const error = new Error('idiolect_region must be a string or null.');
        error.statusCode = 400;
        throw error;
      }
      updates.idiolect_region = updates.idiolect_region.trim() || null;
    }

    if (updates.idiolect_education_level !== undefined && updates.idiolect_education_level !== null) {
      if (typeof updates.idiolect_education_level !== 'string') {
        const error = new Error('idiolect_education_level must be a string or null.');
        error.statusCode = 400;
        throw error;
      }
      updates.idiolect_education_level = updates.idiolect_education_level.trim() || null;
    }

    if (updates.archetype_id !== undefined && updates.archetype_id !== null) {
      if (!isValidHexId(updates.archetype_id)) {
        const error = new Error('archetype_id must be a valid hex ID or null.');
        error.statusCode = 400;
        throw error;
      }
    }

    if (updates.archetype_source_character !== undefined && updates.archetype_source_character !== null) {
      if (!isValidHexId(updates.archetype_source_character)) {
        const error = new Error('archetype_source_character must be a valid hex ID or null.');
        error.statusCode = 400;
        throw error;
      }
    }

    if (updates.archetype_generation !== undefined) {
      const val = Number(updates.archetype_generation);
      if (isNaN(val) || !Number.isInteger(val) || val < 1 || val > 10) {
        const error = new Error('archetype_generation must be an integer between 1 and 10.');
        error.statusCode = 400;
        throw error;
      }
      updates.archetype_generation = val;
    }

    const setClauses = [];
    const values = [];
    let paramIndex = 1;

    for (const [field, value] of Object.entries(updates)) {
      setClauses.push(field + ' = $' + paramIndex);
      values.push(value);
      paramIndex++;
    }

    setClauses.push('updated_at = CURRENT_TIMESTAMP');
    values.push(characterId);

    const updateQuery = 'UPDATE character_personality SET ' +
      setClauses.join(', ') +
      ' WHERE character_id = $' + paramIndex +
      ' RETURNING *';

    const result = await pool.query(updateQuery, values);

    if (result.rows.length === 0) {
      const error = new Error('Character personality not found.');
      error.statusCode = 404;
      throw error;
    }

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character personality updated', {
      characterId,
      updatedFields: Object.keys(updates),
      dangerZone: hasDanger,
      durationMs: duration
    });

    res.json({
      success: true,
      personality: result.rows[0]
    });

  } catch (error) {
    next(error);
  }
});


/* ============================================================================
 * POST /:id/inventory/transfer — Transfer object to another character
 * ============================================================================
 * Moves an object from source character to target character.
 * Logs the transfer in object_transfer_history.
 * Enforces single ownership (DB UNIQUE constraint on object_id).
 * ============================================================================ */

router.post('/:id/inventory/transfer', async (req, res, next) => {
  const startTime = performance.now();
  const client = await pool.connect();

  try {
    const fromCharacterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(fromCharacterId)) {
      const error = new Error('Invalid source character ID format.');
      error.statusCode = 400;
      throw error;
    }

    const { object_id, to_character_id, transfer_reason, new_binding_type } = req.body;

    if (!object_id || !isValidHexId(object_id)) {
      const error = new Error('object_id is required and must be a valid hex ID.');
      error.statusCode = 400;
      throw error;
    }

    if (!to_character_id || !isValidHexId(to_character_id)) {
      const error = new Error('to_character_id is required and must be a valid hex ID.');
      error.statusCode = 400;
      throw error;
    }

    if (fromCharacterId === to_character_id) {
      const error = new Error('Cannot transfer an object to the same character.');
      error.statusCode = 400;
      throw error;
    }

    await client.query('BEGIN');

    const inventoryResult = await client.query(
      'SELECT inventory_entry_id, slot_trait_hex_id, binding_type FROM character_inventory WHERE character_id = $1 AND object_id = $2 FOR UPDATE',
      [fromCharacterId, object_id]
    );

    if (inventoryResult.rows.length === 0) {
      await client.query('ROLLBACK');
      const error = new Error('Object not found in source character inventory.');
      error.statusCode = 404;
      throw error;
    }

    const currentEntry = inventoryResult.rows[0];

    const targetResult = await client.query(
      'SELECT character_id FROM character_profiles WHERE character_id = $1',
      [to_character_id]
    );

    if (targetResult.rows.length === 0) {
      await client.query('ROLLBACK');
      const error = new Error('Target character not found.');
      error.statusCode = 404;
      throw error;
    }

    const transferId = await generateHexId('object_transfer_id');

    await client.query(
      'INSERT INTO object_transfer_history (transfer_id, object_id, from_character_id, to_character_id, transfer_reason, transferred_by, previous_binding_type, new_binding_type) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)',
      [
        transferId,
        object_id,
        fromCharacterId,
        to_character_id,
        transfer_reason || 'admin_transfer',
        'admin',
        currentEntry.binding_type,
        new_binding_type || currentEntry.binding_type,
      ]
    );

    await client.query(
      'UPDATE character_inventory SET character_id = $1, source_character_id = $2, acquired_at = CURRENT_TIMESTAMP, acquisition_method = $3, binding_type = $4 WHERE inventory_entry_id = $5',
      [
        to_character_id,
        fromCharacterId,
        'transfer',
        new_binding_type || currentEntry.binding_type,
        currentEntry.inventory_entry_id,
      ]
    );

    await client.query('COMMIT');

    const duration = Math.round(performance.now() - startTime);

    logger.info('Object transferred', {
      transferId,
      objectId: object_id,
      fromCharacterId,
      toCharacterId: to_character_id,
      reason: transfer_reason || 'admin_transfer',
      durationMs: duration
    });

    res.json({
      success: true,
      transfer: {
        transfer_id: transferId,
        object_id: object_id,
        from_character_id: fromCharacterId,
        to_character_id: to_character_id,
        transfer_reason: transfer_reason || 'admin_transfer',
      }
    });

  } catch (error) {
    try { await client.query('ROLLBACK'); } catch (rollbackErr) { /* already rolled back */ }
    next(error);
  } finally {
    client.release();
  }
});


/* ============================================================================
 * PUT /:id/knowledge-state — Update character knowledge state
 * ============================================================================
 * Editable: last_review_timestamp, acquisition_method, is_mastered,
 *   is_forgotten, acquisition_completed, practice_count
 * Read-only (FSRS algorithm): current_retrievability, stability, difficulty,
 *   next_review_timestamp, current_expertise_score, grade_history, memory_trace
 * ============================================================================ */
router.put('/:id/knowledge-state', async (req, res, next) => {
  const startTime = performance.now();

  try {
    const characterId = decodeURIComponent(req.params.id);

    if (!isValidHexId(characterId)) {
      const error = new Error('Invalid character ID format.');
      error.statusCode = 400;
      throw error;
    }

    const { knowledge_id } = req.body;

    if (!knowledge_id || !isValidHexId(knowledge_id)) {
      const error = new Error('knowledge_id is required and must be a valid hex ID.');
      error.statusCode = 400;
      throw error;
    }

    const EDITABLE_FIELDS = [
      'last_review_timestamp', 'acquisition_method',
      'is_mastered', 'is_forgotten', 'acquisition_completed', 'practice_count'
    ];

    const updates = {};

    for (const key of EDITABLE_FIELDS) {
      if (req.body[key] !== undefined) {
        updates[key] = req.body[key];
      }
    }

    if (Object.keys(updates).length === 0) {
      const error = new Error('No valid fields provided for update.');
      error.statusCode = 400;
      throw error;
    }

    if (updates.practice_count !== undefined) {
      const v = Number(updates.practice_count);
      if (isNaN(v) || !Number.isInteger(v) || v < 0) {
        const error = new Error('practice_count must be a non-negative integer.');
        error.statusCode = 400;
        throw error;
      }
      updates.practice_count = v;
    }

    if (updates.acquisition_method !== undefined) {
      if (updates.acquisition_method !== null) {
        const trimmed = String(updates.acquisition_method).trim();
        if (trimmed.length > 50) {
          const error = new Error('acquisition_method must be 50 characters or fewer.');
          error.statusCode = 400;
          throw error;
        }
        updates.acquisition_method = trimmed || null;
      }
    }

    if (updates.is_mastered !== undefined) {
      updates.is_mastered = Boolean(updates.is_mastered);
    }

    if (updates.is_forgotten !== undefined) {
      updates.is_forgotten = Boolean(updates.is_forgotten);
    }

    if (updates.acquisition_completed !== undefined) {
      updates.acquisition_completed = Boolean(updates.acquisition_completed);
    }

    if (updates.last_review_timestamp !== undefined) {
      if (updates.last_review_timestamp !== null) {
        const d = new Date(updates.last_review_timestamp);
        if (isNaN(d.getTime())) {
          const error = new Error('last_review_timestamp must be a valid date or null.');
          error.statusCode = 400;
          throw error;
        }
        updates.last_review_timestamp = d.toISOString();
      }
    }

    const setClauses = [];
    const values = [];
    let paramIndex = 1;

    for (const [key, val] of Object.entries(updates)) {
      setClauses.push(key + ' = $' + paramIndex);
      values.push(val);
      paramIndex++;
    }

    values.push(characterId);
    values.push(knowledge_id);

    const updateQuery = 'UPDATE character_knowledge_state SET ' + setClauses.join(', ') + ' WHERE character_id = $' + paramIndex + ' AND knowledge_id = $' + (paramIndex + 1);

    const result = await pool.query(updateQuery, values);

    if (result.rowCount === 0) {
      const error = new Error('Knowledge state not found for this character and knowledge item.');
      error.statusCode = 404;
      throw error;
    }

    const duration = Math.round(performance.now() - startTime);

    logger.info('Character knowledge state updated', {
      characterId,
      knowledgeId: knowledge_id,
      fieldsUpdated: Object.keys(updates),
      durationMs: duration
    });

    res.json({
      success: true,
      updated: Object.keys(updates)
    });

  } catch (error) {
    next(error);
  }
});

export default router;
