/**
 * =============================================================================
 * StudentComponent — TSE Human Input Pass-Through (Human Users Only)
 * =============================================================================
 *
 * WHAT THIS MODULE IS:
 * ---------------------------------------------------------------------------
 * Receives human input from the socket layer and packages it into a
 * structured attempt object for EvaluatorComponent to score. This is a
 * deliberate pass-through — the human IS the student.
 *
 * HUMAN-ONLY BOUNDARY:
 * ---------------------------------------------------------------------------
 * This module is used ONLY for human user learning.
 * NO autonomous/B-Roll/NPC learning occurs here.
 * NO auto-generated student responses.
 * NO AI-generated answers.
 *
 * Human input arrives via socket → TSELoopManager → StudentComponent → Evaluator.
 *
 * Claude's language learning (from users) belongs in:
 *   backend/services/learningCapturer.js (v010)
 *
 * WHY A PASS-THROUGH EXISTS:
 * ---------------------------------------------------------------------------
 * The TSE pipeline expects Teacher → Student → Evaluator. In a B-Roll
 * context, StudentComponent would generate AI responses. For human users,
 * it wraps their real input into the same attempt shape so Evaluator
 * receives a consistent contract regardless of source.
 *
 * This also provides a single validation gate for empty/malformed input
 * before it reaches the evaluation layer.
 *
 * CONSUMED BY:
 * ---------------------------------------------------------------------------
 *   TSELoopManager.js — calls learn(characterId, knowledgeId, task, humanInput)
 *
 * ATTEMPT OBJECT CONTRACT (consumed by EvaluatorComponent):
 * ---------------------------------------------------------------------------
 *   {
 *     attemptId: string,       // hex ID from tse_attempt_id range
 *     taskId: string|null,     // from task object
 *     characterId: string,     // character hex ID (e.g. Claude #700002)
 *     knowledgeId: string|null,// knowledge item being tested
 *     attemptText: string,     // the human's actual answer
 *     metadata: {
 *       outcome_intent: string,
 *       humanInput: true,
 *       autoGenerated: false,
 *       correlationId: string|null
 *     }
 *   }
 *
 * v010 STANDARDS:
 * ---------------------------------------------------------------------------
 *   - Structured logger with createModuleLogger (no console.log)
 *   - Counters on learn() (.success, .empty_rejected, .error)
 *   - Input validation on hex IDs via isValidHexId
 *   - Correlation ID threading via opts parameter
 *   - Frozen constants
 *   - Named export alongside default for tree-shaking compatibility
 *   - No Math.random() — no nodeId needed for pass-through
 *
 * =============================================================================
 */

import generateHexId, { isValidHexId } from '../utils/hexIdGenerator.js';
import { createModuleLogger } from '../utils/logger.js';
import Counters from '../councilTerminal/metrics/counters.js';

/* ==========================================================================
 * Constants
 * ========================================================================== */

const MODULE_NAME = 'StudentComponent';

const DEFAULTS = Object.freeze({
  OUTCOME_INTENT_FALLBACK: 'neutral'
});

const logger = createModuleLogger(MODULE_NAME);

/* ==========================================================================
 * StudentComponent Class
 * ========================================================================== */

class StudentComponent {

  constructor() {
    // Pass-through component — no state needed
  }

  /* ========================================================================
   * Input Validation
   * ======================================================================== */

  _validateHexId(value, name) {
    if (!value || !isValidHexId(value)) {
      throw new Error(
        `${MODULE_NAME}: invalid ${name} — expected #XXXXXX hex format, got: ${value}`
      );
    }
  }

  /* ========================================================================
   * Main Entry Point
   * ======================================================================== */

  /**
   * Package human input as a student attempt for EvaluatorComponent.
   *
   * This is a PASS-THROUGH. The human IS the student.
   * No auto-generation. No AI responses. Just the human's actual answer
   * wrapped in the attempt contract that Evaluator expects.
   *
   * @param {string} characterId — character hex ID (e.g. Claude #700002)
   * @param {string|null} knowledgeId — knowledge item hex ID (may be null)
   * @param {object} task — task object from TeacherComponent
   * @param {string} humanInput — the actual human input from socket
   * @param {object} opts — { correlationId }
   * @returns {object|null} attempt object for Evaluator, or null if input rejected
   */
  async learn(characterId, knowledgeId, task, humanInput, opts = {}) {
    const correlationId = opts.correlationId || null;
    Counters.increment('tse.student.learn');

    /* --- Validate character ID --- */
    this._validateHexId(characterId, 'characterId');

    /* --- Validate knowledge ID if provided --- */
    if (knowledgeId) {
      this._validateHexId(knowledgeId, 'knowledgeId');
    }

    /* --- Reject empty human input --- */
    if (!humanInput || humanInput.trim().length === 0) {
      Counters.increment('tse.student.learn.empty_rejected');
      logger.warn('Refusing empty input — human must provide an answer', {
        taskId: task?.taskId || 'unknown',
        taskType: task?.taskType || 'unknown',
        correlationId
      });
      return null;
    }

    /* --- Generate attempt ID --- */
    try {
      const attemptId = await generateHexId('tse_attempt_id');

      const attempt = {
        attemptId,
        taskId: task?.taskId || null,
        characterId,
        knowledgeId: knowledgeId || null,
        attemptText: humanInput,
        metadata: {
          outcome_intent: task?.metadata?.target_outcome_intent || DEFAULTS.OUTCOME_INTENT_FALLBACK,
          humanInput: true,
          autoGenerated: false,
          correlationId
        }
      };

      Counters.increment('tse.student.learn.success');
      logger.debug('Human attempt packaged', {
        attemptId,
        taskId: attempt.taskId,
        characterId,
        inputLength: humanInput.length,
        correlationId
      });

      return attempt;

    } catch (error) {
      Counters.increment('tse.student.learn.error');
      logger.error('Failed to package human attempt', error, {
        taskId: task?.taskId || 'unknown',
        characterId,
        correlationId
      });
      return null;
    }
  }
}

export { StudentComponent };
export default StudentComponent;
